using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PMS.Models.Acc;

[Table("Voucher", Schema = "acc")]
public class AccVoucher
{
    public int VoucherID { get; set; }

    public int VoucherTypeID { get; set; }

    [StringLength(30)]
    public string VoucherNo { get; set; } = string.Empty;

    [Column(TypeName = "date")]
    public DateTime VoucherDate { get; set; }

    public int PeriodID { get; set; }

    public int FiscalYearID { get; set; }

    [StringLength(100)]
    public string? ReferenceNo { get; set; }

    [StringLength(1000)]
    public string? Narration { get; set; }

    [Column(TypeName = "decimal(18,2)")]
    public decimal TotalDebit { get; set; }

    [Column(TypeName = "decimal(18,2)")]
    public decimal TotalCredit { get; set; }

    [StringLength(20)]
    public string Status { get; set; } = "Draft";

    public bool IsReversed { get; set; }

    public int? ReversalVoucherID { get; set; }

    public bool IsAutoGenerated { get; set; }

    /// <summary>Optional bank account for BPV/BRV (requires Scripts/AMS_Alter_Voucher_BankAccount.sql).</summary>
    public int? BankAccountID { get; set; }

    [StringLength(50)]
    public string? SourceModule { get; set; }

    [StringLength(10)]
    public string? PMSProjectID { get; set; }

    [StringLength(10)]
    public string? PMSAllotmentID { get; set; }

    [StringLength(10)]
    public string? PMSCustomerID { get; set; }

    public int? PMSDealerID { get; set; }

    [StringLength(10)]
    public string? PMSPaymentID { get; set; }

    [StringLength(10)]
    public string? PMSRefundID { get; set; }

    [StringLength(10)]
    public string? PMSDealerPaymentID { get; set; }

    [StringLength(10)]
    public string? PMSPenaltyID { get; set; }

    [StringLength(50)]
    public string? PMSTransferID { get; set; }

    [StringLength(50)]
    public string? PMSRentalPaymentID { get; set; }

    [StringLength(10)]
    public string CreatedBy { get; set; } = string.Empty;

    public DateTime CreatedAt { get; set; }

    [StringLength(10)]
    public string? SubmittedBy { get; set; }

    public DateTime? SubmittedAt { get; set; }

    [StringLength(10)]
    public string? ApprovedBy { get; set; }

    public DateTime? ApprovedAt { get; set; }

    [StringLength(10)]
    public string? PostedBy { get; set; }

    public DateTime? PostedAt { get; set; }

    [StringLength(10)]
    public string? ReversedBy { get; set; }

    public DateTime? ReversedAt { get; set; }

    [ForeignKey(nameof(VoucherTypeID))]
    public AccVoucherType? VoucherType { get; set; }

    [ForeignKey(nameof(PeriodID))]
    public AccAccountingPeriod? Period { get; set; }

    [ForeignKey(nameof(FiscalYearID))]
    public AccFiscalYear? FiscalYear { get; set; }

    [ForeignKey(nameof(ReversalVoucherID))]
    public AccVoucher? ReversalOf { get; set; }

    [ForeignKey(nameof(BankAccountID))]
    public AccBankAccount? BankAccount { get; set; }

    public ICollection<AccVoucherLine> Lines { get; set; } = new List<AccVoucherLine>();
}
